services:
  dashboard:
    build:
      context: ./dashboard
    ports:
      - "9003:8501"
    volumes:
      - ./dashboard:/app
    devices:
      - /dev/video0:/dev/video0
    working_dir: /app
    command: streamlit run streamlit.py --server.port=8501 --server.address=0.0.0.0
